// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function scr_artistURLArrayOverworld(){
var artistURLArrayOverworld =	[
				"https://discord.gg/nWj8jGEA",		// Row 1
				"https://twitter.com/plutobirdo",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/JonTheRealJon?s=09",
				"https://twitter.com/JonTheRealJon?s=09",
				"https://twitter.com/JonTheRealJon?s=09",
				"https://twitter.com/Oroshibu",
				"https://twitter.com/Elementalisman?t=dTW-q8y9XRnZd80To6bY1g&s=09",
				"https://yaboimatteedubbz.carrd.co/",
				"https://twitter.com/Maytch",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/MageUntalented",
				"https://twitter.com/ddoobysnax/status/1371195606828412929",
				"https://twitter.com/Maytch",
				"https://discord.gg/nWj8jGEA",
				
				"https://crowno.carrd.co/",			// Row 2
				"https://linktr.ee/FloppyVelarde",
				"https://linktr.ee/javve",
				"https://linktr.ee/ShinySeabass",
				"https://twitter.com/PixelsSj",
				" https://linktr.ee/Jameskevich",
				" https://linktr.ee/Jameskevich",
				"https://twitter.com/Oroshibu",
				"https://linktr.ee/lorenradis",
				"https://twitter.com/vvvultures",
				"https://linktr.ee/datpolyb",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/PikaBoooouh",
				"https://linktr.ee/thedragonllama",
				"https://linktr.ee/lorenradis",
				"https://discord.gg/nWj8jGEA",
				
				"https://twitter.com/block_snake",	// Row 3
				"https://linktr.ee/reineke",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/crizzpix",
				"https://twitter.com/crizzpix",
				"https://twitter.com/RaspberryMilks1",
				"https://linktr.ee/illusionofmana",
				"https://linktr.ee/illusionofmana",
				"https://linktr.ee/Dylz49",
				"https://twitter.com/tripleafrog",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://linktr.ee/MerSaloon",
				
				"https://twitter.com/squp_haver",	// Row 4
				"https://linktr.ee/reineke",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/azlef123",
				"https://twitter.com/minichibisart",
				"https://twitter.com/MaxiSZ69",
				"https://twitter.com/TidnBits",
				"https://linktr.ee/illusionofmana",
				"https://linktr.ee/illusionofmana",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/MobyPixel",
				"https://linktr.ee/blindeduif",
				"https://linktr.ee/lorenradis",
				"https://linktr.ee/btdangelo",
				"https://linktr.ee/johndanims",
				
				"https://discord.gg/nWj8jGEA",	// Row 5
				"https://linktr.ee/reineke",
				"https://linktr.ee/reineke",
				"https://twitter.com/j_raido",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/nekofresa",
				"https://twitter.com/ChocoPain",
				"https://twitter.com/kitwahsu",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://linktr.ee/lorenradis",
				"https://discord.gg/nWj8jGEA",
				"https://linktr.ee/blindeduif",
				"https://twitter.com/blind3dbylight",
				"https://twitter.com/blind3dbylight",
				"https://twitter.com/suspixelart?lang=en",
				
				"https://discord.gg/nWj8jGEA",	// Row 6
				"https://twitter.com/MursellJ_art",
				"https://twitter.com/MursellJ_art",
				"https://twitter.com/j_raido",
				"https://www.instagram.com/kumporigin/",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://crowno.carrd.co/",
				"https://linktr.ee/1Sinvilla",
				"https://twitter.com/Alisuca3",
				"https://twitter.com/Alisuca3",
				"https://twitter.com/NHorologiumRPG?s=09",
				"https://linktr.ee/CJJammies",
				"https://twitter.com/blind3dbylight",
				"https://twitter.com/torrybobs",
				"https://twitter.com/suspixelart?lang=en",
				"https://discord.gg/nWj8jGEA",
				
				"https://twitter.com/MursellJ_art",	// Row 7
				"https://twitter.com/MursellJ_art",
				"https://twitter.com/illydinosaur",
				" http://airyu.cat/",
				" http://airyu.cat/",
				" http://airyu.cat/",
				"https://discord.gg/nWj8jGEA",
				"https://twitter.com/tanu_pxl",
				"https://twitter.com/Alisuca3",
				"https://twitter.com/Alisuca3",
				"https://twitter.com/_discocats",
				"https://www.twitter.com/mazzymuse",
				"https://www.twitter.com/mazzymuse",
				"https://linktr.ee/Cloditu",
				"https://yaboimatteedubbz.carrd.co/",
				
				"https://twitter.com/PorbleG",	// Row 8
				"https://twitter.com/K3nch44?s=09",
				"https://twitter.com/illydinosaur",
				"https://twitter.com/illydinosaur",
				"http://airyu.cat/",
				"https://kawaiikimu.carrd.co/",
				"https://linktr.ee/arkflinn",
				"https://linktr.ee/arkflinn",
				"https://twitter.com/re4mat",
				"https://twitter.com/re4mat",
				"https://twitter.com/rose_bushes_",
				"https://twitter.com/DonMarramiau",
				"https://twitter.com/DonMarramiau",
				"https://discord.gg/nWj8jGEA",
				"https://discord.gg/nWj8jGEA",
				"https://linktr.ee/MerSaloon"
				]
	return artistURLArrayOverworld;
}