// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function scr_artistArrayOverworld(){
var artistArrayOverworld =	[
					"Mista Jub",	// Row 1
					"Sarnyoger",
					"HyMyNameIsMatt",
					"shino1",
					"RedRachis",
					"RedRachis",
					"RedRachis",
					"Oroshibu",
					"Elementalisman",
					"YaBoiMatteeDubbz",
					"Maytch",
					"MikManc",
					"TolerableToast",
					"ddooby",
					"Maytch",
					"khyledaniels",
					
					"crowno",		// Row 2
					"FloppyVelarde",
					"javve",
					"ShinySeabass",
					"SJPixels",
					"jamesskevich",
					"jamesskevich",
					"Oroshibu",
					"LorenRadis",
					"vvvultures ",
					"PolyB",
					"MikManc",
					"Enchanteur",
					"thedragonllama",
					"LorenRadis",
					"Roybot",
					
					"SnakeBlock",		// Row 3
					"Reineke",
					"Doki",
					"Sperbs",
					"crizz",
					"crizz",
					"RaspberryMilkshake",
					"IllusionOfMana",
					"IllusionOfMana",
					"-Dylz49-",
					"Jonas Q",
					"Croey",
					"RoyBot",
					"OvergrownRobot",
					"gravityblocks",
					"DumDrums",
					
					"squp",			// Row 4
					"Reineke",
					"Doki",
					"Kiln",
					"minichibis",
					"MaxiSZ",
					"TidnBits ",
					"IllusionOfMana",
					"IllusionOfMana",
					"KiwiComet",
					"Cerberus",
					"Nick Culbertson",
					"Blindeduif",
					"LorenRadis",
					"btdangelo",
					"JohnDAnims",
					
					"ForcaraEvasion",	// Row 5
					"Reineke",
					"Reineke",
					"jRaido",
					"AceCanti",
					"Nekofresa",
					"Maxime",
					"Kitasu",
					"Discodur0",
					"KiwiComet",
					"LorenRadis",
					"Hut",
					"Blindeduif",
					"blind3dbylight",
					"blind3dbylight",
					"sus",
					
					"ForcaraEvasion",	// Row 6
					"MursellJ",
					"MursellJ",
					"jRaido",
					"Kumpo",
					"offbeat",
					"GlacierWold8",
					"crowno",
					"Sinvilla",
					"Arisuki",
					"Arisuki",
					"NHMoon",
					"CJJammies",
					"blind3dbylight",
					"Tori Roberts",
					"sus",
					"efejotart",
					
					"MursellJ",			// Row 7
					"MursellJ",
					"DutchDinosaur",
					"Airyucat",
					"Airyucat",
					"Airyucat",
					"julcreutz",
					"tanu",
					"Arisuki",
					"Arisuki",
					"_discocats",
					"Mazzymuse",
					"Mazzymuse",
					"Cloditu",
					"YaBoiMatteeDubbz",
					
					"Benjamin Wendt",	// Row 8
					"Kenchinator",
					"DutchDinosaur",
					"DutchDinosaur",
					"Airyucat",
					"KawaiiKimu",
					"Arkflinn", 
					"Arkflinn", 
					"re4mat",
					"re4mat",
					"Rosebushes",
					"Daeron",
					"Daeron",
					"ChJa",
					"Mattyace",
					"DumDrums"
				]
	return artistArrayOverworld;
}
